### ISSUE TITLE
virus header

### ISSUE THREAD

**Issue by basbebe** [rspamd/rspamd#1631]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [x ] Not applicable

If the X-Virus header of rmilter_headers.conf would not only add a header with the signature's name but also add a header like "X-Virus-Status: Clean" (like clamav-milter does) then it would be even more easy and comfortable to check with sieve.

**Comment by vstakhov** [comment]
This is doable by 'rmilter_headers' module I believe.

**Comment by bax-** [comment]
yes it is, but only with a user-defined custom routine.
The `X-Virus` header which is accessible out of the box "only" adds a header if a signature has been found:
```
X-Virus: XXXXX
```

I personally find the approach of clamav-milter more explicit:
if nothing is found:
```
X-Virus-Status: Clean
```
If a signature has been found:
```
X-Virus-Status: Infected
X-Virus: XXXXX
```

That is as I said completely personal preference.
If it is easy to do with a custom routine I'm all ears.
Otherwise it might be considered as a out-of-the-box solution.
