### ISSUE TITLE
dkim private key files need be readable by user _rspamd

### ISSUE THREAD

**Issue by mpizzoli** [rspamd/rspamd#1822]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.3

### Operation system, CPU, memory and environment:
EL7 x86_64

### Description (Please provide a descriptive summary of the issue):
Following this discussion on the Postfix mailing list:
http://postfix.1071664.n5.nabble.com/What-user-should-be-specified-for-the-opendikm-u-UID-option-td92395.html
I notice that rspamd does not deal with the privilege drop in reading private keys files. They need to be owned by the user _rspamd, otherwise it can't read them.

### Compile errors (if any):
N/A

### Steps to reproduce:
Try using dkim private key files owned by root and then try to dkim-sign emails

### Expected results:
emails get signed 

### Actual results:
rspamd unable to open the private key files

### Debugging information (see details [here](https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed)):
N/A

### Configuration:
N/A

### Additional information:
N/A

**Comment by vstakhov** [comment]
They can be owned by any user but `_rspamd` user needs permission to read the keys. Reading keys before dropping of root privs can be implemented in theory by worker<->main interaction but it is not obviously a high priority task.

**Comment by joskar** [comment]
I have same problem. 

But the confusing part is that even I switched my logging level to warning/info/error the logging didn't say to me anything useful.

![image](https://user-images.githubusercontent.com/2728259/42757409-a1cb9fae-8908-11e8-8313-f47d0de501cc.png)

In the end I edited the line [159 of dkim_signing.lua](https://github.com/vstakhov/rspamd/blob/1.7.8/src/plugins/lua/dkim_signing.lua#L159) in order to show more information.

But when I saw the error `permission denied` which is even more confusing because the key file is owned by the `_rspamd` user and it has 440 permissions.

**Comment by vstakhov** [comment]
Are you using the recent version of Rspamd? https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd

What if you check access directly, e.g. `sudo -u _rspamd ls -l /path/to/key`

**Comment by joskar** [comment]
I'm using the version 1.7.8 on a Debian stretch machine (the link on the my previous comment is on that tag :)). 
In my `/etc/rspamd/local.d/logging.inc` I already have `debug_modules I have debug_modules = [ "dkim_signing", "dkim" ];` which is the weirdest part, because I believed with this way I would be able to see all messages (debug, warning, errors) from that the specified modules.

When I run:
`su - _rspamd -c "ls -l /var/lib/rspamd/dkim/2018.key"`

The command didn't return anything! and if I `echo $?` it shows me `1`
I'm thinking that this might be a special issue because I'm running with inside an lxc container.

**Comment by vstakhov** [comment]
Some path component is likely unavailable for reading I suppose.

**Comment by joskar** [comment]
Apparently it was a permission problem. While the key file had 440 permission the dkim directory didn't have the correct permissions...

**Comment by bellegarde-c** [comment]
This one is strange. Opendkim refused to run if private key is not secure and rspamd refused to run if private key is secure.

**Comment by vstakhov** [comment]
So much secure to be unreadable by Rspamd?

**Comment by bellegarde-c** [comment]
Opendkim read the key before dropping root priv. If an attacker is able to run a shell (buf overflow, ...), it will be as opendkim user and so will not be able to read the key.

It's not a critical issue BTW ;)

**Comment by andryyy** [comment]
Why is it insecure to have them readable for _rspamd? That's non sense and kind of pseudo security.

**Comment by vstakhov** [comment]
If a key is already in memory you are still doomed tbh. The only way of protecting something in memory is to use like SGX enclave or something similar.

**Comment by vstakhov** [comment]
But what I clearly see is some usability improvement - that's true.

**Comment by kgggggb** [comment]
same problem, my system `Ubuntu 22.04.1`, `Rspamd daemon version 3.4`, 
when i checking `dkim status` using `postfix` to send email, gmail doesn't have signed via dkim, 
![image](https://user-images.githubusercontent.com/47137779/209452101-f40907d3-389b-4d8e-b10a-a9b46ac8531a.png)

and [mail test](https://www.mail-tester.com/) said `Your message is not signed with DKIM`, 
![image](https://user-images.githubusercontent.com/47137779/209452115-7e561451-1e6b-4ffe-a150-6e29cfabc43d.png)

so i `tail -f /var/log/rspamd/rspamd.log`, saw this: `proxy; dkim_module_load_key_format: cannot load dkim key : cannot stat key file: '' Permission denied`, i figure it out somehow `_rspamd` user needs `execution permission of dkim folder`, dkim files like .private in this case, doesn't need it, weird. so i **keep owner to root** and set **directory permission** to `645`, **dkim files** permission to `644`, now it works fine.
![image](https://user-images.githubusercontent.com/47137779/209452131-f097744b-8d79-4805-b738-d0188593754b.png)
![image](https://user-images.githubusercontent.com/47137779/209452148-5e9000b6-b8a4-4fb3-82f1-48018159b098.png)
