### ISSUE TITLE
integration Peekaboo and cuckoo

### ISSUE THREAD

**Issue by smindorf** [rspamd/rspamd#1860]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [X] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [ ] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [X] Not applicable

Is it planed or already possible to integrate [Peekaboo](https://github.com/scVENUS/PeekabooAV) and [cuckoo](https://cuckoosandbox.org) into Rspamd?

Regards,
Sören

**Comment by vstakhov** [comment]
Peekaboo wants files to be scanned which. In theory, it is possible with tmpfs but it's not the best way to scan data. Cuckoo seems to be fine by https://cuckoo.sh/docs/usage/api.html#tasks-create-submit

Anyway, adding these AV engines is not in my TODO list so far.

**Comment by heraklit256** [comment]
I would be interested in that topic, too.

**Comment by yoshimo** [comment]
Maybe integrating the logic of https://github.com/sbidy/MacroMilter would be easier and faster to do and more efficient than a big approach like Cuckoo Sandbox

**Comment by yoshimo** [comment]
Peekaboo relies on Amavis capabilities to extract  and handle attachments that it then processes.
They wrote a patch for Amavis to have necessary details like a filename as well.
So if you wanted to use it with rspamd i guess there is additional functionality for attachments that you would have to include in rspamd.

**Comment by c-rosenberg** [comment]
Rspamd can easily provide the attachment, filename and attachment metadata. If you could receive the data and meta info over a socket, this would be great.

**Comment by vstakhov** [comment]
Well, all I need is a protocol specification. Even rough, like clamav "has": https://linux.die.net/man/8/clamd

**Comment by yoshimo** [comment]
@michaelweiser is that something you can help with?

**Comment by michaelweiser** [comment]
Sorry for letting this sit for so long. I was hoping to get around to write up some proper documentation I could point you to and perhaps even improve the protocol to get rid of local file access and transfer file contents directly. This has not happened. :-/ In the meantime I can give you the following description as a first impression of the status quo:

We are listening to a UNIX domain stream socket, on Linux typically `/run/peekaboo/peekaboo.sock`. When a client connects to that socket, it is expected to send a JSON structure like this:

```
            [ { "full_name": "<path>",
                "name_declared": ...,
                ... },
              { ... },
              ... ]
```

This array of hashes lists all the files to be scanned for malware. Each hash has to contain at least the key `full_name`. This is the absolute path to the file to be scanned. Peekaboo expects to be able to open this file for reading (permissions). This file has to persist until the analysis has finished. Other possible keys can provide additional information about the file:

* `name_declared`: is expected to be the name declared in the MIME metadata of an attachment.
* `type_declared`: is expected to be the MIME type declared in the metadata of an attachment.

Both are strings. Further keys may be specified in the future but only these two are supported currently.

The client is expected to keep the socket connection open until Peekaboo has reported its verdict.

Multiple files can be listed as individual hashes. These form a batch and are expected to be attachments belonging to the same email. In addition to the individual scan results per file, Peekaboo will provide an overall verdict for the whole batch. This is written as plain text to the UNIX domain socket back to the client. Typical output looks like this:

```
Hello, this is Peekaboo.

File "scan_file.py" 21a76f46ef42a2649d91ad49038a4e239511f4e0b6cd110120348d1d66a130bf is being analyzed
File "scan_file.py": Result "failed" of rule RulesetEngine - Rule aborted with error, analysis continues: No.
File "scan_file.py" is considered "failed"

File "scan_emailed_file.py" b1e9895c98463891f89b59c3021a07d0eb295d215fa594a80379e7f324bccdb4 is being analyzed
File "scan_emailed_file.py": Result "failed" of rule RulesetEngine - Rule aborted with error, analysis continues: No.
File "scan_emailed_file.py" is considered "failed"

The file collection has been categorized "failed"
```

The last line in particular is meant to be latched on to by some sort of pattern matching to determine whether analysis found malware, failed due to some internal problem or did not find anything suspicious. Possible keywords are:
* `bad`: malware found
* `failed`: analysis failed due to some internal problem
* `ignored`: no analysis was done because the file type or some other property was on a whitelist
* `unknown`: no determination could be made either way, which also includes the case that analysis concluded successfully but no malware was found

Output can be localised in order to be presented to end users or admins. The last line "The file collection..." will however always be included in this manner in addition to any localized version.

Implementations of clients for this protocol for reference are:
* https://github.com/scVENUS/PeekabooAV/blob/master/bin/scan_file.py
* https://github.com/scVENUS/PeekabooAV/blob/master/amavis/10-ask_peekaboo

The server side is here:
* https://github.com/scVENUS/PeekabooAV/blob/master/peekaboo/server.py#L139

Hope this is enough to move discussion along or even start implementation. I'd be happy to help with either.

**Comment by michaelweiser** [comment]
Uh, if I didn't make it clear: This protocol is the way it is because currently we control both client and server implementations. So before we implement this more statically in rspamd we can change it whatever way we want without much consideration for backward compatibility because we can just adjust our clients and server to any changes we want to make to the procotol. If possible and/or desired we can also ship the rspamd plugin/client with Peekaboo to more easily keep implementations in sync on future updates to the protocol.

**Comment by vstakhov** [comment]
1) Protocol that relies on files sucks as it doesn't scale across the network. I'd prefer to have some streaming approach if possible.
2) Plain TCP is not the easiest thing to handle, why not use HTTP wrap and act like a REST API.
3) JSON requests are fine but why JSON is not used to produce output? It doesn't make sense to me.

In theory, I can write a client for the existing protocol but it would be definitely ugly and alien for Rspamd.

**Comment by vstakhov** [comment]
Another `+` for (2) is that HTTP could be easily replaced with HTTPS when you need to scale securely.
