### ISSUE TITLE
Integrate the unwanted folder

### ISSUE THREAD

**Issue by MisterM74** [rspamd/rspamd#1914]
### Classification (Please choose *one* option):

* [x] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [ ] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.6.5
### Operation system, CPU, memory and environment:
Centos
### Additional information:

Hello

I am Zimbra user.
When I realize that I have a spam message I send it myself in the junk mail.
An information is sent to sign in the antispam (spamassassin, or postscreen) that this message is indishable (spam).
Why not do it with RSPAMD, especially since I integrate it with Zimbra?
An idea ...
Mz

**Comment by vstakhov** [comment]
I don't know what are you asking about.

**Comment by MisterM74** [comment]
https://forums.zimbra.org/viewtopic.php?f=15&t=62443&sid=56225ccb52d37a193539c00f8d194b38&start=90#p279834

**Comment by fenice2** [comment]
@MisterM74 

I'm assuming that what you're asking here is the ability to send an email directly to rspamd for training when you hit the "Junk" button in Zimbra, is that correct?

I can't speak for Rspamd but there are a couple of problems doing that from a Zimbra perspective. First, any mail that's in the Junk folder whether it's put there by ZCS (as possible spam) or the user with the Junk button may not actually be spam - it could be a false positive via the ZCS server or the user could have made an error and marked the wrong message as spam.

In the situation I've described above if the user realises they have a false positive or that they've made a mistake they have the option to mark a message as Ham and stop it being trained as spam.

The second problem is that the Junk folder behaviour is part of the Zimbra source code and we can't do anything without rewriting that, this would be something Zimbra would have to do. :)

My opinion is that the current mode of operation of the Zimbra server is best from a user perspective and the anti-spam system gets trained by on overnight cron job, I don't think anything needs changing. I'd be interested to hear what improvement or benefits you think that sending 'spam' directlty to rspamd would give.

**Comment by andryyy** [comment]
I think learning spam by a nightly cronjob is crap. Zimbra really does that? I hope they do not run over the whole mail dir every night without checking for file times or something like that.

But this whole issue is hard to understand. Rspamd is perfectly able to learn ham and spam by using the http api.

If it is not working in Zimbra, this issue should be reported to _them_.

**Comment by fenice2** [comment]
How easily a single "crap" word dismisses something that has been in service for the past twelve years by over 200,000 businesses (one of whom has 10,000,000 users) and the 500,000,000 mailbox users. Yes, Zimbra really does that and it does it well. Perhaps a few words of encouragement would be of benefit rather than outright dismissal, there seems to be too little of the first and too much of the second in this project.

The overnight training script merely extracts mail from a user junk folder (those messages they have marked as spam) and those from the 'ham' folder and trains rspamd with those emails, by their nature there are usually very few of those. In addition the current training script has been converted to use rspamc to train the messages.

I know full well about the http api but if you read my previous post you would have seen that I mentioned 'changes to zimbra source code', this is one of those functions that would require that. Zimbra have not yet accepted my bug report for integrating Rspamd into the ZCS server so my modifications are just a preliminary step to see how rspamd works and perform with ZCS then hopefully we will see some movement on the bug report. I won't hold my breath on that as glaciers seem to move faster than Zimbra (the company). :) When or if rspamd is accepted into Zimbra I'm sure they'll take into consideration of the functions in the Rspamd project and use them to their full advantage.

**Comment by andryyy** [comment]
Zimbra profits, Zimbra pays?

Everything needed for it to work is available in Rspamd. It’s up to Zimbra. Do they want to sponsor it?

**Comment by fenice2** [comment]
Unfortunately I don't speak for Zimbra and the appearance of any senior member (of the company) on the forums is almost non-existent. I am only a user of ZCS and a moderator on the forums, I came across Rspamd when I was looking for a replacement for spamassassin and the now defunct DSPAM. Rspamd was relatively easy to implement in my single server environment and work well for months before I started that thread, it's still a bit of hard work for me as I don't do this for a living but I'm am keen on Rspamd. 

I spent several months trying rspamd on my own server and then created a thread & RFE report to see if anyone was interested in trying/testing Rspamd, if you're interested the my thread is in this forum: https://forums.zimbra.org/viewforum.php?f=15 

FWIW, I'd love to see this project tested then adopted in Zimbra. :)

**Comment by vstakhov** [comment]
Could you please explain me the issue without flooding (I don't understand @MisterM74 in any language I'm afraid)? 

Am I understanding correct that you want to train spam/ham from some specific folders and not cleaning them after training? I think this might be useful as training corpuses are somehow valuable and one doesn't want to remove everything upon train is completed.

On the other hand, this task can be easily solved by a small helper script in shell/perl or delegated to `rspamadm` where you can add your own Lua scripts to manipulate with data. I think the last option is the best one.

**Comment by MisterM74** [comment]
I found, it is necessary to follow the open topic on the forum of Zimbra which is open ..

https://forums.zimbra.org/viewtopic.php?t=62443

I have a question, but nothing to talk about at the moment.

I am looking for a list RBL against phishing, because I am a lot is it annoys me very hard

Mz

**Comment by fenice2** [comment]
@MisterM74 

Have you looked at the phishing module? https://rspamd.com/doc/modules/phishing.html
