### ISSUE TITLE
redefining SPF/DKIM/DMARC symbols

### ISSUE THREAD

**Issue by bjoe2k4** [rspamd/rspamd#2174]
### Classification (Please choose *one* option):
* [x] Enhancement
### Rspamd version:
1.7.3
### Description (Please provide a descriptive summary of the issue):
What is the purpose to be able to "redefine" these symbols, i.e. change their symbol names? I am asking, because currently these symbol names are defined in various lua files, sometimes with redefinitions checked, sometimes not.

file | type | spf | dkim | dmarc | arc
---- | ----- | ----- | ------- | -------- | -----
arc.lua | module | def | def |  none | def/check/conf
spf.c | c-module | def/conf | none | none | none
dkim.c | c-module | none  | none | none | none
dkim_singing.lua | module | none | DKIM_SIGNED | none | none
dmarc.lua | module | def/check | def/check | def/check/conf | none
milter_headers.lua | module | def/conf | def/conf | def/conf | none
lua_auth_results.lua | lib | def/arg | def/arg | def/arg | def/arg
http_headers.lua| module  | def/check | def/check | def/check | none 

What is the reason to be able to change symbol name in `milter_headers`?

Moreover, `gen_auth_results` defined in `lua_auth_results.lua` is called from `milter_headers.lua` with a settings argument, while it's called from `arc.lua` without any settings.

The main issue i am seeing is that these symbol names are hardcoded in many other places as well and changing their names might not be a good idea. I'd propose (options):

- Remove the possibility to redefine symbol names all the way.
- Allow definition of symbol names only from one place (module default settings in *.lua *or* *.conf files, not both, probably the latter) and pull the symbol names from there (just via `rspamd_config:get_module_opt` or `rspamd_config:get_all_opt`). This also applies to a module's default options.

Overall i think this would make configuration a little less confusing and can de-clutter various lua routines.

**Comment by vstakhov** [comment]
That's all a big story of legacy decision made in the past. For now, I'm inclined to disable possibility of vanilla symbols definitions where possible. My motivation is simple: if there is some rule based plugin, it is natural to configure symbols for it. For something like SPF, there is no need to redefine anything as it is a part of basic functionality.

Another story is a disambiguation with `R_` prefixed and other symbols. Unfortunately, Rspamd existed for many years and all the time I tried my best to preserve backward compatibility. But the cost of that is quite high: many things are now ugly, unclear and illogical just due to compatibility considerations.
