### ISSUE TITLE
Authentication-Results Header sometimes invalid

### ISSUE THREAD

**Issue by andreasschulze** [rspamd/rspamd#2178]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Serious bug
* [x] Other bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Rspamd version:
1.7.3

### Operation system, CPU, memory and environment:
Linux

### Description (Please provide a descriptive summary of the issue):
Message from a domain that announce a DMARC Policy, but aren't DKIM signed
I get an A-R Header that don't contain an authserv-id
( https://tools.ietf.org/html/rfc7601#section-2.2 )

### Steps to reproduce:
send a message without a dkim signature but that is known to pass SPF
from a domain that announce p=none

### Expected results:
Authentication-Results: mail.example.com;
	dmarc=pass (policy=none) header.from=example.net;
	spf=pass smtp.mailfrom=localpart@example.net

### Actual results:
Authentication-Results: dmarc=pass (policy=none) header.from=example.net;
	spf=pass smtp.mailfrom=localpart@example.net

### Configuration:
mostly defaults but dmarc enabled in local.d/dmarc.conf:
reporting = true;
and A-R header inserting enabled in local.d/milter_headers.conf:
use = ["authentication-results"];

**Comment by bjoe2k4** [comment]
I have proposed a fix to that in https://github.com/vstakhov/rspamd/pull/2134 some time ago.

**Comment by andreasschulze** [comment]
I can confirm the fix solve the issue.
This version add the spamfilter's hostname. Other implementations use the value of milter macro "daemon_name" or apply a user configured value to assist later consumption of the A-R header.

**Comment by bjoe2k4** [comment]
As it just got merged, i'd have to submit another pull request for that. So authservid should be taken in the following order:

1. User configured value, else:
2. daemon_name macro, else:
3. hostname

I've also seen in opendkim the possibility to add the MTA Queue-ID to authservid. Is that considered useful given that it is also present in Received headers (at least for postfix)?

**Comment by bjoe2k4** [comment]
I *would* have to submit another pull request, i.e. i didn't do so yet ;-)

Mainly because there are open questions that need to be addressed:

- Where should such a configuration of the Authentication-Results header go? Right now it is in `milter_headers` module, but there is no configuration possible for the ARC-AR header. Since AR and AAR by definiton should be the same, any changes to AR will create invalid AAR. That's why i think there should be only one configuration for both in a separate configuration file. maybe @vstakhov can help to decide/advise
- header.b addtion sounds like a good idea, but this information is not yet attached to the symbol. I don't have enough C skills to implement such feature. Once it is available i could add the lua part.
