### ISSUE TITLE
SPOOF_REPLYTO(6) disable for own domains?

### ISSUE THREAD

**Issue by SandraCCH** [rspamd/rspamd#2567]
### Classification (Please choose *one* option):

* [] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [x] Serious bug
* [ ] Ordinary bug
* [ ] Feature
* [ ] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

Hi

I have configured a own Mailserver with rspamd 1.8.0 on Debian Stretch.
On a Homepage I send mails with reply to (from sender) and send from my domain with SMTP.
On a other Mailserver with Mailcow, no SPOOF_REPLYTO was set.

On my own configured Mailserver I get SPOOF_REPLYTO with 6 points. How can i solved, that own domains not get a SPOOF_REPLYTO?

I know, I can make a setup with multimap to accept own domains with a map file and get -20 score. But is this the only way? I hope i have a change to setup rspamd that he no set the SPOOF_REPLYTO in own domains

**Comment by olia-bn** [comment]
If anyone runs into this issue:

The check for set reply-to (which Rsmapd considers a spoof attack) is skipped if From and To are equal as that 'validates the use case' of invisibly redirecting emails because it puts the burden on the sender address to be secured.

We just verified that using the following configuration removed the SPOOF_REPLYTO penalty:
```
From: no-reply@example.org
To: info@example.org
Reply-To: end-user@hotmail.com
```
