### ISSUE TITLE
Why is default score DMARC_POLICY_REJECT so small (2.0)?

### ISSUE THREAD

**Issue by analogic** [rspamd/rspamd#2746]
I have one customer which is complaining that his administrator was able to deliver email without DKIM and SPF. I know I can simply multiply score, but what interest me is why the decission was so low. 

From our logs there are like 0.2% of DMARC failing emails which mostly ends up in quarantine anyway but properly composed email without DKIM and failing SPF which look like paypal(p=reject) notice will be probably delivered. Are there any corner cases I don't see?

**Comment by vstakhov** [comment]
This decision has been made due to lots of broken DMARC senders. You can use `whitelist` module with `black` or `both` values in the maps to penalise missing/violated DMARC more for particular domains. However, for the generic domains the score of DMARC violation should not be significantly higher (however, that should be increased to `3.0` I suppose).
