### ISSUE TITLE
dnswl.org integration

### ISSUE THREAD

**Issue by pipiche38** [rspamd/rspamd#2798]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [x] Enhancement

dnswl.org has a service to which we can report spam. It would be great if rspamd could integrate such service and automatically report spam (when rejecting)

**Comment by tjharman** [comment]
For what it's worth, I hope this isn't added (sorry)
I am a firm believer in taking the hash of mails and reporting those automatically, so that **bulk** mail can be detected.
But I'm against automatically reporting anything as spam (or ham)

A newsletter goes out for example and, for whatever reason has enough mistakes in it to be marked spam, even if it's not.  That then getting reported as spam automatically just causes more harm than good.

**Comment by heraklit256** [comment]
Personally, I like the idea but have some objections against it.

As mentioned by @tjharman, mails may be misclassified. Worse, large automated reporting clusters may cause a sort of DoS during a spam wave (not sure if DNSWL.org infrastructure could handle that much traffic).

There may be privacy concerns (for both sender and recipient) - especially when it comes to misclassified messages which are leaked to a 3rd party.
