### ISSUE TITLE
Postfilters for slow external services

### ISSUE THREAD

**Issue by vstakhov** [rspamd/rspamd#2800]
### Classification (Please choose *one* option):

* [ ] Crash/Hang/Data loss
* [ ] WebUI/Usability
* [ ] Unintended behaviour (bug)
* [x] Enhancement

### Reproducibility (Please choose *one* option):

* [X] Always
* [ ] Sometimes
* [ ] Rarely
* [ ] Unable
* [ ] I didn’t try
* [ ] Not applicable

### Description (Please provide a descriptive summary of the issue):

Reduce heavy scanners usage by moving them to postfilter and executing them merely for greymail, excluding clear spam and clear ham.

**Comment by vstakhov** [comment]
https://github.com/HeinleinSupport/rspamd/commit/ad225b16942012abc062e208fe7ba6f9a44b572c

**Comment by spacefreak86** [comment]
How is the current status of this code? Is it still in development?
We use rspamd to reject e-mails due to SPF fail or DMARC fail with reject policy.
The antivirus module is also in use. Currently, every e-mail passes the antivirus module, even if the e-mail is rejected due to SPF- or DMARC fail.

A lot of e-mails are rejected to tue SPF- or DMARC fail, so this feature would drastically reduce the CPU usage on our systems.

**Comment by vstakhov** [comment]
I have reviewed the patch and I think I can merge it. @c-rosenberg, do you have any objections?

**Comment by c-rosenberg** [comment]
Maybe these limits should be configure-able. 

https://github.com/HeinleinSupport/rspamd/commit/ad225b16942012abc062e208fe7ba6f9a44b572c#diff-fb40024cb0234dec1c2eaa860c686591R327

Next to that i'm still fine with the patch.

**Comment by spacefreak86** [comment]
Thanks alot for merging this. Unfortunately, the state in the master branch is not working, because the function check_metric_results is missing within common.lua and therefore, lua scanners are not executed at all if configured for dynamic_scan.

The following error messages appears:
lua_redis_push_data: call to callback failed: /usr/share/rspamd/lualib/lua_scanners/clamav.lua:160: attempt to call field 'check_metric_results' (a nil value)

The commit above adds this function. Please merge it to master as soon as possible.
