### ISSUE TITLE
[BUG] CTYPE_MIXED_BOGUS applies to normal text attachments

### ISSUE THREAD

**Issue by aletheia7** [rspamd/rspamd#3071]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

A plain text email with an attached text file triggers the CTYPE_MIXED_BOGUS(1.00) symbol. When the content-type is multipart/mixed and has two text/plain parts, the symbol is increased +1. There isn't anything strange, or "BOGUS", about sending a text email with a text/plain attachment.

I would like to recommend that this rule be removed in the default configuration.

Thank you for making rspamd!

rspamd_config.CTYPE_MIXED_BOGUS is defined in headers_checks.lua .

### Steps to Reproduce

1. Send a text email with a text file attachment. Check that the email was sent with the Content-Type: multipart/mixed and has two mime parts of text/plain.

**Expected behavior**

CTYPE_MIXED_BOGUS would be removed.

### Versions

1.9.4

### Additional Information

This symbol can be made ineffective by making a file entitled "headers_group.conf" with the following contents:
```
symbols {
  CTYPE_MIXED_BOGUS {
    score = 0
  }
}
```

**Comment by ceo** [comment]
what happened with this issue ? 

what does CTYPE_MIXED_BOGUS mean ?

**Comment by rpv-tomsk** [comment]
Catch the same issue, but in much more critical form: both R_MIXED_CHARSET(9.82){} and CTYPE_MIXED_BOGUS(1.00){} symbols are triggered by a email with plain text attachment. Resulted sum of 10.82 is too high for clean mail.

Additionaly, email has SUBJECT_ENDS_QUESTION(1.00){} - as result mail hits 11.4 score, just because it has plain text attachment. But that email is absolutely clean. Something wents completely wrong. 

An example attached. That is another email, but it also hits R_MIXED_CHARSET (5.689655) + CTYPE_MIXED_BOGUS (1):
[mail.txt](https://github.com/rspamd/rspamd/files/5443449/mail.txt)

What can you recommend? Is this could be fixed in Rspamd, or we should disable R_MIXED_CHARSET locally?

**Comment by rpv-tomsk** [comment]
@vstakhov , Could this issue be reopened or should I open new one?

**Comment by rpv-tomsk** [comment]
Sorry for the noise. The issue not reproduced on rspamd-2.6. 

Thanks for your product, Vsevolod and the Team.
