### ISSUE TITLE
[Feature] Add json log format support

### ISSUE THREAD

**Issue by xkill** [rspamd/rspamd#3095]
## Summary

In order to ingress the logs into elasticsearch, graylog, ... JSON format is a god idea.

## Motivation

I tried to format JSON on the log but I was not able, I don't know how to filter "special" chars such as double quotes or $.

## Describe alternatives you've considered

Allow to scape special characters on the log format. So it can be possible to write a log format like json.

**Comment by vstakhov** [comment]
XY problem, closing.

**Comment by lingfish** [comment]
> XY problem, closing.

What does that even mean?  XY?

**Comment by vstakhov** [comment]
And my answer is effectively the same: logging is not designed for that purposes.

**Comment by lingfish** [comment]
What is your definition of the purpose of logging then?

Mine: The purpose of logging is to log information. Your software already logs to a file. Logging different formats to different destinations/outputs/channels is no different to a file.

Why do you insist that logging to anything but local disk is not the right purpose of logging?!

Perhaps if you could define what you think X and Y are here, those of us not understanding your point might understand better.

**Comment by vstakhov** [comment]
`Y` - a structured information stream about some system's state. `X` - logging. Logging is **unstructured** by definition. Yes it has some structured fields, such as timestamp, logging tag, but otherwise this information depicts the internal messages of the system and is not expected to be structured.

If you want a structured stream of data, do not use logging. E.g. Rspamd supports exporting of the structured data to Elasticsearch (and that was mentioned in the original issue by the way).

If you want to split log messages (bear in mind, those messages will still be unstructured) by their structured tags and emit JSON to disk or to some networking stream, it is doable and even quite easy to do. However, I do not have this task on top of my priority list.

**Comment by lingfish** [comment]
This is now about semantics it seems.

> Yes it has some structured fields, such as timestamp, logging tag

Indeed.  So although I see your point that some of the content of *your* logs aren't necessarily structured, logs generically *are*.

This is best illustrated by example, and a perfect example of it is the [GELF format](https://go2docs.graylog.org/5-0/getting_in_log_data/gelf.html#GELFPayloadSpecification).  The "structured" components are put into fields like `version`, `host` and `full_message`.  Anything else that could be structured, say like the rspamd module (`milter, proxy, task, lua`) then go into the `_[additional field]` construct.

Anything else that is "random" and not structured, goes into `short_message` or `full_message`.

Much like a syslog message... fields include timestamp, host, program name, pid.. and then "the rest of the message".  That is literally **structured**, just like rspamd's default logs are.

> Rspamd supports exporting of the structured data to Elasticsearch (and that was mentioned in the original issue by the way).

And you'll also note I mentioned that I've already implemented that, hence I already acknowledged your point there.  The metadata is one thing (very useful).  Being able to centralise and parse rspamd logs is another.

One can implement network syslog via rsyslogd (which I have also done).  I've even implemented a rsyslogd exporter to push it to Graylog in GELF format!  But... it's just like the above "dumb" syslog example... no smarter field parsing.

Meanwhile, I'm going to attempt to implement the GELF format for metadata via lua; I've achieved sending JSON metadata using the `http` backend to a Graylog raw imput, but each send hangs because rspamd expects (rightly) to talk HTTP (`200 OK` etc) and the GL raw input doens't send anything back, being raw.
