### ISSUE TITLE
Documentation on how to change DBDIR and other Rspamd variables

### ISSUE THREAD

**Issue by mconigliaro** [rspamd/rspamd#3319]
## Summary

Apologies if this is already answered elsewhere, but I couldn't find any documentation on how to change the [Rspamd variables](https://www.rspamd.com/doc/configuration/index.html#rspamd-variables). The closest thing I was able to find was a comment on #1609. 

## Motivation

I'd like to move the Bayes classifier training data to a persistent storage volume so I can rebuild my personal mail server instance without losing anything. I'm pretty sure this data lives in `DBDIR` (i.e. `/var/lib/rspamd` on Ubuntu).

[This comment](https://github.com/rspamd/rspamd/issues/1609#issuecomment-298195493) suggests it's possible to do something like: 

    rspamd -c /etc/rspamd/rspamd.conf DBDIR=/other/path

Which tells me I should be able to override this line in the systemd config file on Ubuntu: 

    ExecStart=/usr/bin/rspamd -c /etc/rspamd/rspamd.conf -f

Is this still the recommended procedure, or is there a better way?

**Comment by phi1010** [comment]
Can a comment reopen this? (The settings module as mentioned in #1609 will not help on shared hosting, where centralized settings cannot be changed, and rsyncd should run from a prefix such as ~/.local. Replacing the configuration options does not work, since even outside the config and lua files, rsyncd seems to access hardcoded /var/...-paths, where a non-root user cannot read or write.)

**Comment by sneak** [comment]
An answer to this would be helpful.

**Comment by fatalbanana** [comment]
Usually it's defined at build time; but setting for e.g. `DBDIR` in environment should work too.
