### ISSUE TITLE
[Feature] Redis SSL/TLS Support

### ISSUE THREAD

**Issue by pere1012** [rspamd/rspamd#3435]
## Summary

SSL/TLS Support for Redis.

## Motivation

Since the passwords for Redis are transmitted in plain text, it would be theoretically possible that they are intercepted and thus data within the Redis database can be changed. This could have the consequence that emails are erroneously let through or blocked.

Redis now supports SSL/TLS since version 6: https://redis.io/topics/encryption
Hiredis meanwhile also supports SSL/TLS: https://github.com/redis/hiredis#ssltls-support

## Describe alternatives you've considered

We have tried Spiped, but since we have several scanners and redis databases, this quickly becomes confusing and time-consuming.

**Comment by vstakhov** [comment]
We have tested TLS support in Redis and it generally sucks. No session cache, no SSL tickets, lot's of bugs. We decided to keep the existing stunnel/nginx proxying as they do their job well. Similarly, I have also no plans to sync hiredis to the upstream.

**Comment by aleshaczech** [comment]
Hi @vstakhov , 

if I understand correctly your recommendation, you are suggesting to use stunnel on both rspamd and Redis sides to encrypt the transit. If that's the case, I'd like to challenge that this is sufficient.

I run my services in K8s cluster and use Redis managed by my cloud provider. Since I don't have Redis under my control, there's no way how I can install stunnel on the Redis side. That means there's no way for me to achieve encryption, not even using service mesh such as istio (because that will encrypt only traffic inside the K8s cluster). The only solution is to install and manage my own Redis server and put it in my K8s cluster. (In my case I use DigitalOcean, but this would be the case for every cloud provider.)

Every major protocol these days supports encryption. Same as I wouldn't stunnel HTTP or connect to MySQL through stunnel, I don't see a good reason why to consider tunneling Redis connection via stunnel as future-proof. Given the pressure on encryption and security of PII, this might be a major blocker for many companies who need their data to be fully encrypted in transit.

If I have missed something or if you think I should open a new issue rather than commenting on a closed one, please let me know, thank you!
