### ISSUE TITLE
[Feature] Add DMARC munging support

### ISSUE THREAD

**Issue by vstakhov** [rspamd/rspamd#3647]
We want Rspamd to be able to perform DMARC munging like Mailman does: https://mailman.readthedocs.io/en/release-3.1/src/mailman/handlers/docs/dmarc-mitigations.html

Probably not for embedded messages.

**Comment by vstakhov** [comment]
It is now implemented and tested in the actual mailing lists.

**Comment by janforth** [comment]
Trying to activate dmarc munging for my mm3 leaves me back with this error message:
2023-04-29 07:41:58 #426735(main) <c1sabr>; lua; lua_redis.lua:581: use default Redis settings for dmarc
2023-04-29 07:41:58 #426735(main) <c1sabr>; lua; dmarc.lua:534: dmarc reporting is enabled
2023-04-29 07:41:58 #426735(main) <yitn31>; map; rspamd_map_add: added map /etc/rspamd/maps.d/dmarc_munging.inc
2023-04-29 07:41:58 #426735(main) <c1sabr>; lua; lua_maps_expressions.lua:125: cannot add maps combination for module dmarc: required elements are missing

What elements can be missing?

**Comment by nlegaillart** [comment]
> Trying to activate dmarc munging for my mm3 leaves me back with this error message: 2023-04-29 07:41:58 #426735(main) ; lua; lua_redis.lua:581: use default Redis settings for dmarc 2023-04-29 07:41:58 #426735(main) ; lua; dmarc.lua:534: dmarc reporting is enabled 2023-04-29 07:41:58 #426735(main) ; map; rspamd_map_add: added map /etc/rspamd/maps.d/dmarc_munging.inc 2023-04-29 07:41:58 #426735(main) ; lua; lua_maps_expressions.lua:125: cannot add maps combination for module dmarc: required elements are missing
> 
> What elements can be missing?

I just got the same issue, using the example provided in the [official documentation](https://rspamd.com/doc/modules/dmarc.html#dmarc-munging). It seems to be caused by the line
```
munge_map_condition = nil; # maps expression to enable munging
```

Assuming setting `nil` is the same as not setting it at all, I just commented it out and the error disappeared.

I'm no Lua expert, so I do not know if doing this right or wrong. Anyway, as the provided example above does not seem to work outside-of-the-box, maybe it should be fixed?
