### ISSUE TITLE
[BUG] ThoughInput do not count soft reject

### ISSUE THREAD

**Issue by thefiredragon** [rspamd/rspamd#3654]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
ThroughInput do not list stats about soft reject, all time count at 0.
Under history lot's of soft rejects are listesd

### Steps to Reproduce

1. Configure rspamd
2. Take a look to your history tab in web 
3. Take a look to the ThoughInput Tab

### Versions

Rspamd daemon version 2.7

**Comment by moisseev** [comment]
It is not exactly a bug.
For some reason these soft rejected messages are counted  in Troughput as `greylist`. It is historical.
Check related soft rejected mails in History, they should have `GREYLIST` symbol.
This happens because `greylist` in History and Throughput has different meanings:
- `greylist` in History means the message was greylisted previously and now it has passed spam flter (special case of `no action`).
- `greylist` in Throughput mean the message was soft rejected due to greylisting (special case of `soft reject`).
