### ISSUE TITLE
[BUG] update module : certificate on updates.rspamd.com has expired

### ISSUE THREAD

**Issue by darthmaul0181** [rspamd/rspamd#3714]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**

Error when update module tries to download :

error reading https://updates.rspamd.com/rspamd-2.ucl(88.99.142.95:443): connection with http server terminated incorrectly: ssl connect error: ssl error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed

### Additional Information

The certificate on https://updates.rspamd.com/ is expired since 27-01-2021

**Comment by vstakhov** [comment]
Please don't use outdated Rspamd versions or at least do not seek for support for those versions here.

**Comment by Lekensteyn** [comment]
For those confused, it appears that the `rspamd_update` module is disabled by default:

https://github.com/rspamd/rspamd/blob/2944572017edb0b5660eb311c9342d19c8737387/conf/modules.d/rspamd_update.conf#L15-L21

If you did not manually enable it, then you must be running a very old version of rspamd since this module was disabled in 1.8.2 (November 2018) according to the ChangeLog file. @darthmaul0181 You should upgrade to a more recent rspamd version.

**Comment by vstakhov** [comment]
Yes, exactly, thank you for the detailed explanation.

**Comment by darthmaul0181** [comment]
The version I use is 2.7. It's the latest one I think.
