### ISSUE TITLE
rspamd_2.8-0~git50~852f2c7f2~buster_amd64.deb  gets segmentation fault

### ISSUE THREAD

**Issue by Twilek-de** [rspamd/rspamd#3721]
### Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
After installing rspamd_2.8-0~git50~852f2c7f2~buster_amd64.deb  rspamd crashes with a segmentation fault. Reverting to git49 solves the problem.

**Comment by vstakhov** [comment]
It works for me. Please read https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed

**Comment by hupe90** [comment]
Same thing happened to us.

**Comment by hupe90** [comment]
I tried to reproduce the problem using rspamd-asan and got the following log output

=================================================================
==1857==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f0284eb1bbd bp 0x7fff42c3c830 sp 0x7fff42c3c670 T0)
==1857==The signal is caused by a READ memory access.
==1857==Hint: address points to the zero page.
    #0 0x7f0284eb1bbc in rspamd_mempool_new_ (/usr/lib/rspamd/librspamd-server.so+0x9dbbbc)
    #1 0x7f02847af72c in global constructors keyed to 65535_0_cryptobox.c.o.128531 (/usr/lib/rspamd/librspamd-server.so+0x2d972c)
    #2 0x7f02853bd379 in call_init /build/glibc-vjB4T1/glibc-2.28/elf/dl-init.c:72
    #3 0x7f02853bd475 in call_init /build/glibc-vjB4T1/glibc-2.28/elf/dl-init.c:118
    #4 0x7f02853bd475 in _dl_init /build/glibc-vjB4T1/glibc-2.28/elf/dl-init.c:119
    #5 0x7f02853af0c9  (/lib64/ld-linux-x86-64.so.2+0x10c9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/rspamd/librspamd-server.so+0x9dbbbc) in rspamd_mempool_new_

**Comment by vstakhov** [comment]
I know the reason I think, thank you. I will fix it soon.

**Comment by vstakhov** [comment]
Is it fixed now?

**Comment by Twilek-de** [comment]
Seems to work fine again, thank you!

**Comment by vstakhov** [comment]
Thanks for reporting!
