### ISSUE TITLE
[BUG] 3.0 Segfault crash, no coredump. Asan version wont start

### ISSUE THREAD

**Issue by sjmoller** [rspamd/rspamd#3920]
I'm seeing this is the log during nighttime (log rotate maybe?):

Oct  3 02:15:01 rspam rspamd[154218]: <d025d2>; main; **rspamd_hup_handler**: rspamd 3.0 is requested to reload configuration
Oct  3 02:15:01 rspam rspamd[154218]: <>; lua; lua_cfg_transform.lua:161: group excessqp has no symbols
Oct  3 02:15:01 rspam rspamd[154218]: <>; lua; lua_cfg_transform.lua:161: group excessb64 has no symbols
Oct  3 02:15:01 rspam rspamd[154218]: <>; lua; lua_cfg_transform.lua:511: enable `options.check_all_filters` for neural network
Oct  3 02:15:01 rspam rspamd[154218]: <>; lua; lua_cfg_transform.lua:569: converted surbl rules to rbl rules
Oct  3 02:15:01 rspam rspamd[154218]: <>; lua; lua_cfg_transform.lua:583: converted emails rules to rbl rules
Oct  3 02:15:01 rspam rspamd[154218]: <>; cfg; rspamd_rcl_maybe_apply_lua_transform: configuration has been transformed in Lua
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; cfg; rspamd_config_set_action_score: action add header has been already registered with priority 0, override it with new priority: 0, old score: nan
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; cfg; rspamd_config_set_action_score: action reject has been already registered with priority 0, override it with new priority: 0, old score: nan
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; lua_redis.lua:574: use default Redis settings for neural
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin neural; register webui path learn
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin maps; register webui path query_specific
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin maps; register webui path query
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin maps; register webui path list
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin selectors; register webui path list_extractors
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin selectors; register webui path check_selector
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin selectors; register webui path list_transforms
Oct  3 02:15:01 rspam rspamd[154218]: <7h4fd3>; lua; init.lua:58: controller plugin selectors; register webui path check_message
Oct  3 02:15:02 rspam rspamd[154218]: <7h4fd3>; cfg; rspamd_language_detector_init: loaded 46 languages, 33122 trigramms
Oct  3 02:15:02 rspam rspamd[154218]: <d025d2>; main; reread_config: replacing config
Oct  3 02:15:02 rspam rspamd[154218]: <7h4fd3>; cfg; chartable_module_config: init internal chartable module
Oct  3 02:15:02 rspam rspamd[154218]: <7h4fd3>; cfg; rspamd_init_filters: reconfig of chartable
Oct  3 02:15:02 rspam rspamd[154218]: <7h4fd3>; cfg; dkim_module_config: init internal dkim module
Oct  3 02:15:02 rspam rspamd[154218]: <7h4fd3>; cfg; rspamd_init_filters: reconfig of dkim
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; **rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault)**, pid: 154218, trace: 
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 0: 00007FBE7C1B529A: __nss_database_lookup()+0x2195a
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 1: 00007FBE7C941571: ucl_hash_search()+0xf1
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 2: 00007FBE7C8702C4: regexp_module_config()+0x2d4
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 3: 00007FBE7C759946: rspamd_init_filters()+0x206
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 4: 000056203ACB5341: <unknown>
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 5: 00007FBE7C368B96: ev_invoke_pending()+0x56
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 6: 00007FBE7C36C64F: ev_run()+0x72f
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 7: 000056203ACA2B42: <unknown>
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 8: 00007FBE7C07FD0A: __libc_start_main()+0xea
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_print_crash: 9: 000056203ACA308A: <unknown>
Oct  3 02:15:02 rspam rspamd[154218]: <>; ; rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
Oct  3 02:15:02 rspam rspamd[154219]: <d025d2>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
Oct  3 02:15:02 rspam rspamd[154221]: <d025d2>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
Oct  3 02:15:02 rspam rspamd[154223]: <d025d2>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
Oct  3 02:15:02 rspam rspamd[154220]: <d025d2>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
Oct  3 02:15:02 rspam rspamd[154220]: <>; ; rspamd_controller_on_terminate: closing rrd file: /var/lib/rspamd/rspamd.rrd
Oct  3 02:15:02 rspam rspamd[154222]: <d025d2>; main; rspamd_worker_term_handler: terminating after receiving signal Terminated
Oct  3 02:15:02 rspam rspamd[1225993]: 2021-10-03 02:15:02 #1225993(main) <684f43>; main; main: rspamd 3.0 is loading configuration, build id: release

If I try the ASAN version, I get this error:

Oct  3 10:38:23 rspam rspamd[1292192]: =================================================================
Oct  3 10:38:23 rspam rspamd[1292192]: ==1292192==ERROR: AddressSanitizer: odr-violation (0x7f0866216ac0):
Oct  3 10:38:23 rspam rspamd[1292192]:   [1] size=1 'piecewise_construct' /usr/include/c++/10/bits/stl_pair.h:83:53
Oct  3 10:38:23 rspam rspamd[1292192]:   [2] size=1 'piecewise_construct' /usr/include/c++/10/bits/stl_pair.h:83:53
Oct  3 10:38:23 rspam rspamd[1292192]: These globals were registered at these points:
Oct  3 10:38:23 rspam rspamd[1292192]:   [1]:
Oct  3 10:38:23 rspam rspamd[1292192]:     #0 0x55ec990f3a00  (/usr/bin/rspamd+0x6ba00)
Oct  3 10:38:23 rspam rspamd[1292192]:     #1 0x7f0865b06969  (/usr/lib/rspamd/librspamd-server.so+0x38f969)
Oct  3 10:38:23 rspam rspamd[1292192]:     #2 0x7f086664ffe1 in call_init elf/dl-init.c:72
Oct  3 10:38:23 rspam rspamd[1292192]:   [2]:
Oct  3 10:38:23 rspam rspamd[1292192]:     #0 0x55ec990f3a00  (/usr/bin/rspamd+0x6ba00)
Oct  3 10:38:23 rspam rspamd[1292192]:     #1 0x7f0863e35581  (/usr/lib/rspamd/librspamd-replxx.so+0x75581)
Oct  3 10:38:23 rspam rspamd[1292192]:     #2 0x7f086664ffe1 in call_init elf/dl-init.c:72
Oct  3 10:38:23 rspam rspamd[1292192]: ==1292192==HINT: if you don't care about these errors you may set ASAN_OPTIONS=detect_odr_violation=0
Oct  3 10:38:23 rspam rspamd[1292192]: SUMMARY: AddressSanitizer: odr-violation: global 'piecewise_construct' at /usr/include/c++/10/bits/stl_pair.h:83:53
Oct  3 10:38:23 rspam rspamd[1292192]: ==1292192==ABORTING

### Versions

Lastest stable 3.0 (as of Oct 3 2021).
OS: Linux rspam 5.10.0-8-amd64 #1 SMP Debian 5.10.46-5 (2021-09-23) x86_64 GNU/Linux
CPU:
  processor       : 0
  vendor_id       : GenuineIntel
  cpu family      : 6
  model           : 85
  model name      : Intel(R) Xeon(R) Silver 4208 CPU @ 2.10GHz
  stepping        : 7
  microcode       : 0x5003003

### Additional Information

This this not happen on Debian 10 kernel 4.19.
Can be reproduced by issuing a HUP to rspamd main process on a Debian 11.

**Comment by sjmoller** [comment]
Update:
It turns out that I can actually reproduce this by issuing a kill -1 <pid> to the main process.

**Comment by tschiex** [comment]
It looks like I have the same (or a closely related) issue. This happened already in 2.7 with the Ubuntu provided (yes, I know it's not really appreciated here) rspamd package on ARM64 (but rspamd does not provide ARM64 packages I think? Would be happy t ouse it otherwise). 

I grabbed the rspamd 3.0 debian package from rspamd repo and recompiled from source on my ARM64 machine: same behavior (add to play a bit with doctest, required 2.4.6 version). I failed producing cores (despite following the FAQ, says throttles=no ???, wee below). I did not try ASAN (as it had been done already).

2021-10-17 16:41:41 #73575(normal) <fe84c0>; task; rspamd_message_parse: loaded message; id: <614b1cf4-8d96-8fae-a130-16dd59ca17ed@xxx.xx>; queue-id: <684bd70d>; size: 1585; checksum: <74ec6a2caf9f057bd08d7f5648ae2b0e>
2021-10-17 16:41:41 #73575(normal) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 73575, trace: 
2021-10-17 16:41:41 #73575(normal) rspamd_print_crash: 0: 0000FFFF94C0F7A4: <unknown>
2021-10-17 16:41:41 #73575(normal) rspamd_print_crash: 1: 000000000037DBC0: <unknown>
2021-10-17 16:41:41 #73460(main) <cf250f>; main; rspamd_check_termination_clause: normal process 73575 terminated abnormally with exit code 0 by signal: Segmentation fault but NOT created core file (throttled=no); core file limits: 0 current, -1 max
2021-10-17 16:41:41 #73460(main) <cf250f>; main; rspamd_cld_handler: respawn process normal in lieu of terminated process with pid 73575
...
2021-10-17 16:46:43 #73612(normal) <0bcef7>; task; rspamd_url_text_extract: got empty text part
2021-10-17 16:46:43 #73612(normal) rspamd_crash_sig_handler: caught fatal signal 11(Segmentation fault), pid: 73612, trace: 
2021-10-17 16:46:43 #73612(normal) rspamd_print_crash: 0: 0000FFFF94BDF87C: <unknown>
2021-10-17 16:46:43 #73612(normal) rspamd_print_crash: 1: 0000FFFF94C1C6D0: <unknown>
2021-10-17 16:46:43 #73612(normal) rspamd_crash_sig_handler: please see Rspamd FAQ to learn how to dump core files and how to fill a bug report
2021-10-17 16:46:43 #73460(main) <cf250f>; main; rspamd_check_termination_clause: normal process 73612 terminated abnormally with exit code 0 by signal: Segmentation fault but NOT created core file (throttled=no); core file limits: 0 current, -1 max

This seems to happen only with incoming traffic. DKIM signing outgoing traffic looks fine.
