### ISSUE TITLE
[BUG] Failure to unlink stale cache file results in map not being used

### ISSUE THREAD

**Issue by kartoffelheinz** [rspamd/rspamd#4238]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Read about bug reporting in general: https://rspamd.com/doc/faq.html#how-to-report-bugs-found-in-rspamd
    * Enabled relevant debugging logs: https://rspamd.com/doc/faq.html#how-to-debug-some-module-in-rspamd 
    * Checked the FAQs about Core files in case of fatal crash: https://rspamd.com/doc/faq.html#how-to-figure-out-why-rspamd-process-crashed
    * Tried ASAN package and obtained the ASAN report (if possible): https://rspamd.com/doc/faq.html#asan-builds 
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Arspamd
    * Checked that there is not already an experimental package or master branch

**Describe the bug**
We use a bunch of simple regex maps on a remote https location to facilitate updating. There are regular updates on the files. This works fine... until it doesn't. At some point, rspamd runs into problems deleting already deleted the local cache files. As to why this happens I have no clue, maybe a race condition if multiple workers detect remote changes? But it happens on ALL of the systems we run or maintain (about 10 with rspamd instances). This could be addressed in another issue if you like.

The issue we have problems with then is, once rspamd decides it cannot unlink the stale cache file, it will refrain from using the map at all. This sometimes  results in a huge spam spike - or, worse - the rejection of originally whitelisted senders/servers from these maps.

Sample logline (note: this is NOT being logged as an error. Loglevel for this should be changed to error imo)

> Aug  8 11:31:13 spamgateway1 rspamd[42259]: <97zdui>; map; rspamd_re_map_cache_cleanup_old: cannot unlink stale cache file for https://rspamd.ourdomain.de/maps/blacklist_from_header_re.txt (/var/lib/rspamd//786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419.hsmc): No such file or directory

Edit: What makes me wonder is that there isn't any .hsmc file in /var/lib/rspamd at all. Not even after a reload.

Rspamd retries this a few times then gives up and will not use the configured map until a daemon reload.

### Steps to Reproduce

I'm not really sure how to exactly reproduce this as it only happens from time to time, the setup usually is as follows:

1. Use a map from some https location, e.g. (snippet from multimap.conf)
`my_bl_from_re {
    type = "header";
    header = "from";
    regexp = true;
    map = "https://rspamd.ourdomain.de/maps/blacklist_from_header_re.txt";
    symbol = "MY_BL_FROM";
    prefilter = true;
    action = reject;
    description = "My blacklist regex map BL_SENDER";
}`
2. Update the mapfile on the remote location every now and then for a few days
3. search rspamd.log or mail.log for "cannot unlink stale cache file"

**Expected behavior**
If rspamd is unable to unlink a missing cache file, especially if it detects the file does not exist, the code should assume there was no cachefile in the first place to refresh and just create a new one and use the map as configured.

### Versions

Rspamd daemon version 3.2 on Debian Buster and Bullseye.

**Comment by vstakhov** [comment]
This commit should resolve the issue but I'm not 100% sure that it is not just hiding it...

**Comment by innocenzic** [comment]
Hi, 
we've been facing the same issue described by @kartoffelheinz lately. We'running rspamd as a statefulset on kubernetes 1.32.5, and the rspamd image we're using is rspamd/rspamd:3.11.

This is what we're noticing in logfiles:
1. map gets modified and has a different timestamp
2. rspamd tries to download map (gen mismatch), but we cannot tell if it succeeded or not
3. at some point in time "our modify time" resets to 0 and map no longer gets downloaded
4. after quite a few hours our lua filters return that the map is empty, we do not know why it takes such a long time for the filter to detect that the map is no longer available
5. The only way to restore functionality is by deleting the pod, so that it starts out with a fresh new cache and fresh downloaded files

This is an extract of our logfile:
-  rspamd_map_cache_cb: cached data is now expired (gen mismatch 9 != 10) for http://mylist
-  rspamd_map_read_cached: http://mylist: read map data cached 587904 bytes"
-  rspamd_map_common_http_callback: need to reread cached map triggered by http://mylist (1757347704 our modify time, 1757348985 cached modify time)"
-  rspamd_kv_list_fin: read hash of 13858 elements from http://mylist"
-  rspamd_map_common_http_callback: need to reread cached map triggered by http://mylist (0 our modify time, 1757348985 cached modify time)"
-  rspamd_map_read_cached: http://mylist: read map data cached 587904 bytes"
-  rspamd_kv_list_fin: read hash of 13858 elements from http://mylist"
-  rspamd_map_common_http_callback: need to reread cached map triggered by http://mylist (0 our modify time, 1757348985 cached modify time)"
-  rspamd_map_read_cached: http://mylist: read map data cached 587904 bytes"
-  rspamd_kv_list_fin: read hash of 13858 elements from http://mylist"
-  rspamd_map_common_http_callback: need to reread cached map triggered by http://mylist (0 our modify time, 1757348985 cached modify time)"
-  rspamd_map_read_cached: http://mylist: read map data cached 587904 bytes"
-  rspamd_kv_list_fin: read hash of 13858 elements from http://mylist"
-  rspamd_map_common_http_callback: need to reread cached map triggered by http://mylist (0 our modify time, 1757348985 cached modify time)"
-  rspamd_map_read_cached: http://mylist: read map data cached 587904 bytes"
-  rspamd_kv_list_fin: read hash of 13858 elements from http://mylist"
-  http_map_finish: need to reread map from http://mylist"
... (quite a few hours)
-  our_filter.lua:129: dedicated whitelist not available - no processing"

Lua filter code extract:
        if not dedicated_netblocks_map or dedicated_netblocks_map:get_nelts() == 0 then
            rspamd_logger.infox(task, 'dedicated whitelist not available - no processing' )
            return 0,{}
        end

We're unable to reproduce the issue since it is random, but we expect that the code does not suddenly stop trying to download and update cache file when "our modify time" resets to 0.

Is this the expected rspamd behavior or are we facing a bug?

Regards

**Comment by vstakhov** [comment]
3.11 is outdated and not supported.

**Comment by innocenzic** [comment]
Thank you, we will update version.
Regards
