### ISSUE TITLE
"TLS used?" module

### ISSUE THREAD

**Issue by crepererum** [rspamd/rspamd#427]
## Intro

A brief idea for a new module: "was TLS used to send the mail to a certain server?" ("certain" and not "this", because rspamd might not run on the same system as the SMTP mailbox).
## Process
1. go through all `Received` headers and parse `from <source> by <target> with <protocol>` (open question: how standard is that?)
2. stop if we find a `<target>==SERVER`
3. analyse `<protocol>` to figure out if:
   1. it was encrypted
   2. if so, how good the encryption was
4. based on the previous point, emit score
## Config
- `SERVER`: first SMTP server which is part of "our" system and receives messages from the outer world
- `SCORE_INSECURE`: score for unencrypted transport and broken ciphers
- `SCORE_SECURE`: score for reasonableness secure transport
- `SCORE_HIGHSECURE`: score for high secure ciphers (e.g. forward secure + >=128 symm. key + good mode of the symm. mode + ...)

**Comment by vstakhov** [comment]
I don't like the idea to parse received headers for this purpose since they could be easily forged. In general, your MTA can pass TLS information via HTTP headers (could be done using rmilter, for example). Subsequently, rspamd can read that data via `task:get_request_header(name)` and add symbol based on that information. So everything could be done using just rules.

**Comment by fatalbanana** [comment]
`TLS-Cipher` and `TLS-Version` request headers might be set when Milter interface is used but nothing uses this so far.
