### ISSUE TITLE
[Feature] Add official Rspamd Docker Image

### ISSUE THREAD

**Issue by GevatterGaul** [rspamd/rspamd#4400]
## Summary

Please add an official Docker Rspamd Docker Image or, maybe equally as good, explain why a Rspamd Docker image is a bad idea.

## Motivation

There are multiple Rspamd Docker Images on Dockerhub but they are mostly from 3rd parties where you cannot read the code of the image and have to blindly trust some stranger. An official Rspamd image would make it easier to choose or save the time to build an own image. 

## Describe alternatives you've considered

I wondered wether the rspamd/centos-7/8 images are the official images but could not find anything about them.

I ended up building my own image: https://hub.docker.com/r/gevattergaul/rspamd
Code: https://boredconsultant.com/2022/12/31/How-to-Build-a-Rspamd-Docker-Image/
Usage example: https://boredconsultant.com/2023/02/06/Dockerized-Spam-Filtering-With-Rspamd/

Feel free to use anything helpful from my image to make an official image.

## Additional context

None

**Comment by ckristo** [comment]
Would love to see this! There is a [Dockerfile](https://github.com/rspamd/rspamd/blob/master/docker/Dockerfile) in the repo - is this intended to build a Docker image for productive usage?

**Comment by fatalbanana** [comment]
https://hub.docker.com/r/rspamd/rspamd

https://github.com/rspamd/rspamd-docker

**Comment by polarathene** [comment]
@fatalbanana why is the image configured to [create an anonymous volume for `/var/lib/rspamd`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L30)? Please don't do that [it's wasteful](https://docs.docker.com/engine/reference/builder/#volume). You already instruct on the [DockerHub page](https://hub.docker.com/r/rspamd/rspamd) to bind mount this location, no need for implicitly created anonymous volumes (_containers persist internal state during their lifetime anyway?_).

Additionally:
- [This `RUN mkdir`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L13) shouldn't be necessary for the `COPY` after it to work.
- Your final stage makes little sense too with the [`COPY / /`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L26) and could likely be avoided.
- [This `FROM` stage](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L5) is also not needed, you can reference it directly in your [`COPY --from=`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L14). You may also be interested in using `COPY --link --from=` in this case too.
- Why are you running the [image with a random user ID](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L28)? This can be done with `docker run --user 11333:11333`, or for better compatibility `docker run --user "$(id -u):$(id -g)"` (_runs as the current user UID + GID_), no need for the `USER` in docker file, leave it to run as root by default.
- `EXPOSE` is basically for documenting ports, it's not required for functionality. [These exposed ports](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L34) could reference equivalent docs via comment in the `Dockerfile` for additional context (_DockerHub page is also good for that, as-is the Github source README_):
  - `11332` + `11333`: https://www.rspamd.com/doc/workers/rspamd_proxy.html
  - `11334`: https://www.rspamd.com/doc/workers/controller.html
- [These ENV](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L10-L11) don't seem necessary at all to declare. You have them as build `ARG`, they're treated as runtime ENV only. Since you discard this stage anyway, the ENV aren't persisted into the final image stage and they don't seem like they'd provide any value doing so, you only need the `ARG`.

**Comment by fatalbanana** [comment]
Hi,

Thank you for your feedback.

> @fatalbanana why is the image configured to [create an anonymous volume for `/var/lib/rspamd`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L30)? Please don't do that [it's wasteful](https://docs.docker.com/engine/reference/builder/#volume). You already instruct on the [DockerHub page](https://hub.docker.com/r/rspamd/rspamd) to bind mount this location, no need for implicitly created anonymous volumes (_containers persist internal state during their lifetime anyway?_).

It might be better that we have a volume to write to in case one isn't provided. If one would provide one as suggested it wouldn't hurt.

> * [This `RUN mkdir`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L13) shouldn't be necessary for the `COPY` after it to work.

Yes.

> * Your final stage makes little sense too with the [`COPY / /`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L26) and could likely be avoided.

We need that to squash the image (and remove the package in particular).

> * [This `FROM` stage](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L5) is also not needed, you can reference it directly in your [`COPY --from=`](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L14). You may also be interested in using `COPY --link --from=` in this case too.

OK.

> * Why are you running the [image with a random user ID](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L28)? This can be done with `docker run --user 11333:11333`, or for better compatibility `docker run --user "$(id -u):$(id -g)"` (_runs as the current user UID + GID_), no need for the `USER` in docker file, leave it to run as root by default.

We prefer not to start Rspamd as root. The UID/GID is picked so there is a clear UID/GID to assign to directories which might live outside of the container. It can be changed in runtime.

> * `EXPOSE` is basically for documenting ports, it's not required for functionality. [These exposed ports](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L34) could reference equivalent docs via comment in the `Dockerfile` for additional context (_DockerHub page is also good for that, as-is the Github source README_):
>   * `11332` + `11333`: https://www.rspamd.com/doc/workers/rspamd_proxy.html
>   * `11334`: https://www.rspamd.com/doc/workers/controller.html

Is there anything wrong about it?

> * [These ENV](https://github.com/rspamd/rspamd-docker/blob/0790d0f5ea672fa5fa03ad0ee3385b3a80e17b20/Dockerfile#L10-L11) don't seem necessary at all to declare. You have them as build `ARG`, they're treated as runtime ENV only. Since you discard this stage anyway, the ENV aren't persisted into the final image stage and they don't seem like they'd provide any value doing so, you only need the `ARG`.

I'm under impression they need to be declared to be available in the environment (for `RUN dpkg...` stuff).

**Comment by GevatterGaul** [comment]
Thank you so much @fatalbanana !

**Comment by polarathene** [comment]
> It might be better that we have a volume to write to in case one isn't provided. If one would provide one as suggested it wouldn't hurt.

If you don't know why you'd need that, you don't need that 🤷‍♂️ 

As I said, you'll find state is persisted in the container in my experience until the container is removed. The purpose of a volume generally is to persist state beyond that, or to share with other containers, backup etc.

---

> We need that to squash the image (and remove the package in particular).

I didn't check, but are you actually saving that much in storage?

The base image is 80MB (30MB compressed?) IIRC, and by copying all that over from scratch you lose any benefit of sharing the layer. You may unintentionally be making a "larger" image in transit.

You can get a rough compressed size estimate like this:

```bash
docker save my-image-name | gzip -c | wc -c | numfmt --to iec
```

You can either `COPY` + `RUN` a shell script, or use HereDoc syntax to inline:

```Dockerfile
RUN <<EOF
  some-command
  # Look no more `&& \` noise!
  another-command
EOF
```

You can do any other cleanup necessary here really. Use separate `RUN` when you need another layer and want to have those cached / invalidated separately.

- I have an old WIP rspamd builder `Dockerfile` set I was meant to PR for the CI builders repo. It has all these tips applied and can produce quite small images and packages for different distros.
- Another handy feature is `RUN --mount=type=cache` for the package managers to keep their cache out of the image (_no cleanup needed, and no loss from layer invalidation keeping build speedy, especially rspamd builds in CI_).
- For your case `RUN --mount=type=bind` is useful. You can use it to avoid the `COPY --from=stage` for the package, it'll be available during the `RUN` but not persisted into your image layers (_your reason for squashing_).

> Is there anything wrong about it?

Nothing wrong with `EXPOSE`, it's just not necessary beyond communicating ports to a user (_I think there is a command that binds to random ephemeral ports on the host, but that's not something I've ever needed personally_).

Probably better to communicate in DockerHub instructions with additional context. If the ports need to be reachable from external network, they need to be published to a host interface with `-p`.

> I'm under impression they need to be declared to be available in the environment (for RUN dpkg... stuff).

Nope.

Use a tool like [`dive`](https://github.com/wagoodman/dive) to inspect your image layers for that stage (_`docker build --target stage-name ...`_), it'll show that each `RUN` applies the ARG as ENV.

---

> Thank you for your feedback.

You're welcome :)

If you're interested in my rspamd CI `Dockerfile` work I could try find time to publish that this month. I am just not sure when I'll have time for getting back to it and it's been sitting there for 6 months or so getting stale 😬 

It uses `docker bake` to parametize builds and perform them in parallel. I don't have ARM64 system or rspamd dev experience, but ideally they'd have been used to build packages for other distros that were lacking official repo support. In particular I was interested in seeing Fedora supported as a result.

**Comment by gmta** [comment]
@polarathene interesting insights!

Regarding `VOLUME`, to my knowledge this creates an anonymous volume if you don't override it manually, which can be very helpful to indicate the directories which keep state. I am usually happy to see it being used in images since they're not always documented. As far as I know, there is no practical downside to using `VOLUME`. if you know of one/some, I'd love to know.

Same for `EXPOSE`: this will bring the port numbers in view with commands like `docker (compose) ps`, even if you haven't forwarded them. Very useful if you want to have a quick overview of the available ports. And again, no known practical downsides as far as I know. Why not use the standard tooling next to the documentation (which has a different format/style from project to project)?

**Comment by fatalbanana** [comment]
> If you don't know why you'd need that, you don't need that 🤷‍♂️

I'm under impression it's supposed to perform better.

> I didn't check, but are you actually saving that much in storage?

The packages are worth ~43MB.

> The base image is 80MB (30MB compressed?) IIRC, and by copying all that over from scratch you lose any benefit of sharing the layer. You may unintentionally be making a "larger" image in transit.

Right, it should better be a layer on top of the base image; I'd like to fix that.

> * Another handy feature is `RUN --mount=type=cache` for the package managers to keep their cache out of the image (_no cleanup needed, and no loss from layer invalidation keeping build speedy, especially rspamd builds in CI_).

We're currently limited by old (2020) version of docker in docker available in drone docker plugin.

> > I'm under impression they need to be declared to be available in the environment (for RUN dpkg... stuff).
> Nope.

They really are in the environment that we have.

**Comment by polarathene** [comment]
> Regarding `VOLUME`, to my knowledge this creates an anonymous volume if you don't override it manually, which can be very helpful to indicate the directories which keep state.
> I am usually happy to see it being used in images since they're not always documented. 

How are you using this as a user for it to be helpful? If you're reading the `Dockerfile`, then a comment is far better if the project doesn't bother to better document advised mount points.

> As far as I know, there is no practical downside to using `VOLUME`. if you know of one/some, I'd love to know.

Personally, I don't enjoy anonymous volumes being created on my system implicitly. This adds storage that often isn't even necessary.

```Dockerfile
# Clone https://github.com/coredns/coredns
# Replace the Dockerfile with this one
FROM golang:1.21 AS builder

WORKDIR /src
COPY ./ /src
RUN make

# These paths use quite a bit of storage, for demonstration purposes:
VOLUME /go/pkg
VOLUME /root/.cache/go-build
```

```console
$ docker build --tag voltest .
$ docker images
REPOSITORY                        TAG       IMAGE ID       CREATED          SIZE
voltest                           latest    194e456adc3a   1 minutes ago    3.19GB

# 8 seconds or longer to start container with an NVMe disk
# (due to writing a copy of data to anonymous volume)
$ docker run -it --name throwaway voltest bash

# Create a file, exit and stop the container
# (Stopping the container is 10s but unrelated to disk I/O)
$ touch hello && exit && docker stop throwaway

# File still exists in container,
# (even though no volume was mounted to this directory)
$ docker start throwaway
$ docker exec throwaway ls hello
hello

# Look at the data we copied to anonymous volumes:
$ du -shx /go/pkg
1.7G    /go/pkg
$ du -shx /root/.cache/go-build
574M    /root/.cache/go-build

# Here is the anonymous volumes disk usage from these two:
$ docker system df
TYPE            TOTAL     ACTIVE    SIZE      RECLAIMABLE
Local Volumes   2         2         2.201GB   0B (0%)
```

For every container instance I start, there will be two new anonymous volumes created with a large chunk of data.
- Is it helpful? No it slows down that creation of the container, the data is already in the image layer so I'm wastefully writing an entire copy to disk even though I may never write much data to that volume.
- If I use `docker run --rm` (_which I almost always do_), the container is discarded after it stops. The volumes will be too which is helpful, but I never needed them in this case since they're not going to persist afterwards, but I still incur the delay and storage usage while the container is running.
- If I don't use `--rm`, now I need to be mindful of this build up in storage if I just use `docker run image_name` instead of recycling that stopped container, this will really pile up...
- Not an issue if I mount my own volumes with `-v`, but should users be penalized implicitly by not providing explicit mounts? No.

If you want to persist data do so within the existing container and it'll handle that when the container stops, and the state will be gone when the container is removed instead of lingering. Because you're not likely to find anonymous volumes too insightful when it comes to finding which one had that important data for a container you ran but removed a few days ago?:

```console
# Imagine this being a much larger list:
$ docker volume ls
DRIVER    VOLUME NAME
local     45c5448fd503984a08593b11a5d22150d6e7b2ef97685e752b2a4c90b200543f
local     fb8f37ce75ca1bd1c7ad0f70158b695480515c81722954fa6cfe9e5456a013f7

# Very insightful...
$ docker volume inspect 45c5448fd503984a08593b11a5d22150d6e7b2ef97685e752b2a4c90b200543f
[
    {
        "CreatedAt": "2023-10-03T22:04:07Z",
        "Driver": "local",
        "Labels": {
            "com.docker.volume.anonymous": ""
        },
        "Mountpoint": "/var/lib/docker/volumes/45c5448fd503984a08593b11a5d22150d6e7b2ef97685e752b2a4c90b200543f/_data",
        "Name": "45c5448fd503984a08593b11a5d22150d6e7b2ef97685e752b2a4c90b200543f",
        "Options": null,
        "Scope": "local"
    }
]
```

In fairness, Docker Desktop UI for Volume management is much better there and will give you size of the volume and the ability to inspect the contents (_I'm on WSL2 atm, where the `Mountpoint` path is not valid to inspect via terminal_).

I'm usually on a linux system and work with Docker only via the terminal, especially when managing servers over SSH. At least we have good pruning commands these days that you can easily clean this up.

---

> Same for `EXPOSE`: this will bring the port numbers in view with commands like `docker (compose) ps`, even if you haven't forwarded them. Very useful if you want to have a quick overview of the available ports.

Sometimes, but personally either the ports are fairly standard / expected like `80` for a web service, or they've chosen something else for reasons like running as non-root user. Ideally the image is better documented.

In this scenario, I don't know much about rspamd myself, and the port numbers were not recognizable to me. I understood that rspamd probably used them somewhere, but what value is provided from the `EXPOSE` here to me? If I'm going to forward them, I probably would need to go look through documentation first to find out what they're even for, since it's not always wise to publish ports publicly just because they're listed in `EXPOSE`.

Here's an example where too many ports in `EXPOSE` requires a long terminal width (_**EDIT:** slight typo on my part with the last port_):

```console
$ docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED          STATUS          PORTS                                                                                           NAMES
61507cce52b9   voltest   "bash"    36 seconds ago   Up 35 seconds   25/tcp, 110/tcp, 143/tcp, 465/tcp, 587/tcp, 993/tcp, 995/tcp, 11332/tcp, 11334/tcp, 13333/tcp   modest_goldberg
```

vs shorter width:

![image](https://github.com/rspamd/rspamd/assets/5098581/65e53b43-2ce0-4682-8d83-0111fc2cba70)

> And again, no known practical downsides as far as I know.
> Why not use the standard tooling next to the documentation (which has a different format/style from project to project)?

`EXPOSE` isn't as bad, and rarely will you have projects with the length issue like I showed (_valid for one I work on_).

It's a guide though when those ports are "defaults", but config supports using different ports. Like stated earlier, if you don't know what the port is for, you'll probably want to lookup the docs regardless as without any context beyond `EXPOSE`, the information isn't too insightful. Some projects bind to ports that can be useful for local access but a security exploit if published to a public interface.

FWIW, the docs on [`EXPOSE`](https://docs.docker.com/engine/reference/builder/#expose) suggest to only list ports that should be published (_which `-P` can automate, although I don't find it useful myself_). In a project I work on, there are many other ports open than listed above, but those wouldn't be ones that should be published. We provide good documentation on the ports and example configs for the ports to publish.

I get the gripe about varying documentation, I just don't think `EXPOSE` adequately conveys sufficient information unless you already know what the ports represent (_but then how helpful is the `EXPOSE` info?_).

**Comment by polarathene** [comment]
> I'm under impression it's supposed to perform better.

Measure it. I don't think you'll find a meaningful difference though?

Usually depends on storage driver and where the writes are being done. On macOS and Windows, that may matter more (_I think bind mounts to host filesystem instead of the VM filesystem is less performant?_).

I'm pretty sure there is no advantage over explicit volumes though which should be encouraged.

> They really are needed in the environment that we have (which is the only setup I've been bothered to test).

I guess it may be due to the older Docker version you're running.

```Dockerfile
FROM alpine
ARG HELLO=world
RUN echo "${HELLO}" > hello_world.txt
```

```console
$ docker build -t arg-test .
# Output resolved the ARG:
 => [2/2] RUN echo "world" > hello_world.txt
```

From the `dive` tool:

```
RUN HELLO=world /bin/sh -c echo "${HELLO}" > hello_world.txt # buildkit
```
