### ISSUE TITLE
[Feature] Plugin SPF check local IP for external outgoing server

### ISSUE THREAD

**Issue by kepon85** [rspamd/rspamd#4433]
## Summary

That the outgoing servers RSPAMD checks the correct SPF IP (theirs, not that of the "client" - originating server)

## Motivation

In the case of an outgoing server (only) if the local verification of the SPF plugin is activated:
```
check_authed=true
check_local=true
```
The SPF plugin verifies the SPF fields but it compares it with the IP of the client server, of the server from which it originates. Except for the final recipient who will check the SPF field will see the IP of the server on which RSPAMD is installed, he must therefore check with his own IP. (I can draw a diagram if it's not clear..)

The goal here is to only pass clean emails (SPF signature ok) I realize that it's a bit exotic but you propose to force local verification so I tell myself that there is not much missing from a configuration point of view to go to the end ....

## Describe the alternatives you have considered

Currently I'm patching the SPF plugin badly as follows:

```bash
#!/bin/bash
ip=$(hostname -I | cut -d" " -f1)
sed -i "s/task:get_from_ip()/\"${ip}\" --spf-patch.sh/g" /usr/share/rspamd/plugins/spf.lua
```

It's dirty but it works, the outgoing gateways check the local IP (of the server which will send the e-mail out) and not the IP of the server which is entering the e-mail.

Add any other context about the feature request here.

**Comment by fatalbanana** [comment]
Maybe it helps not to tamper with the `local_addrs` setting (and achieve whatever you hope to get out of that by other means, llike `settings` module).

Overall the ask is not wonderfully clear to me. Maybe `external_relay` module is interesting.

**Comment by kepon85** [comment]
Good morning,

I tried playing with external_relay with no success... I can't get it to read the (local) server IP:
```
cannot find external relay for SPF checks in received headers; use the original IP: ${ip}
```

My goal is that it checks the SPF with the IP of the server on which rspamd is running (which is an output-only server) but I may be doing it wrong...

[ MY POSTFIX/DOVECOT SERVER ] > [SENDING GATEWAY WITH RSPAMD] > The world...

On [SENDING GATEWAY WITH RSPAMD] I want to check that the message is indeed SPF signed and that the recording is valid (otherwise I refuse the message) and for that I have to check this with the IP of [GATEWAY D 'SENDING WITH RSPAMD] and not from [ MY POSTFIX/DOVECOT SERVER ] (which is the default, normal behavior)

Maybe it's me who failed to get the external_relay module to work... or my case is too exotic...

Is that any clearer? (sorry, I go through a translator...)

**Comment by fatalbanana** [comment]
There is an option for SPF plugin by this name (which I suggest to ignore) as well as a plugin- the latter should be generally worth looking into, the message you have shown seems to be related to the former: https://www.rspamd.com/doc/modules/external_relay.html - however I don't suppose either is made with your use-case in mind. Deploying DMARC might be more useful than trying to validate your own SPF results.

**Comment by keomabrun** [comment]
Hey, I believe I have the same use case as @kepon85, where I want to make sure that the email going out of my gateway are clean (SPF wise) so that the IP of my gateway does not get a bad reputation.

More context: I host emails for several domains that I don't own. I provide to the domain's owners a documentation on how to configure their DNS zone (mainly SPF, DMARC and DKIM). If they fail configuring their zone and send email through my services, my gateway IP might be flagged as spammer, or at least it will decrease its reputation.
The ideal case for me would be to check emails SPF as they go trough my gateway.

Would you recommend using the `external_relay` module for such use case ? And if yes, how would you avoid getting into the error message described earlier ?

**Comment by fatalbanana** [comment]
SPF module is intended to check sender policy on message receipt, not produce a hypothesized view of how people might see your mail. One could set sending IP to the expected outbound IP but it wouldn't work properly for purposes other than SPF, you might use a dedicated call for that.

You might delay activating accounts until setups are validated / periodically re-validate those somewhere. You might penalize sending domains that aren't expected to pass SPF (so that you would not send such messages) or force return path to be the username in MTA if that's a fully-qualified address (so that they would likely pass SPF).

**Comment by keomabrun** [comment]
That makes sense. Thank you @fatalbanana for the answer :pray:
