### ISSUE TITLE
[Feature] Add support for Ubuntu 24.04: add packages to official repo

### ISSUE THREAD

**Issue by uschindler** [rspamd/rspamd#5040]
I accidentally upgraded my server to Ubuntu 24.04 without first checking that there's an updated version in Rspamd's repo. The version provided for Ubuntu Jammy did not work and failed to install due to misisng dependencies.

Downgrading to the Ubuntu-Provided version causes configuration issues.

So I decided to run dpkg-buildpackage on the master branch: This worked after adding some missing libraries. After installation of deb packages I had rspamd 3.9.0 (snapshot) running. So basically, the build works fine.

It would therefore be great to release packages for Ubuntu 24.04 "noble" in the official repository.

**Comment by julian-klode** [comment]
This is already done: https://github.com/rspamd/rspamd-build-scripts/commit/9cac5f6a61829dbb5c79d7a7f87804d2e147c3f6

The problem seems to be that no release has been cut since February, and I guess they can''t run the build script on the existing one to build stuff that is missing or whatever.

I must say the Ubuntu provided one works ok for me, I upgraded shortly before the 24.04 release. The web UI is completely shot - switching tabs doesn't do anything, but the filtering works.

**Comment by uschindler** [comment]
> This is already done: [rspamd/rspamd-build-scripts@9cac5f6](https://github.com/rspamd/rspamd-build-scripts/commit/9cac5f6a61829dbb5c79d7a7f87804d2e147c3f6)
> 
> The problem seems to be that no release has been cut since February, and I guess they can''t run the build script on the existing one to build stuff that is missing or whatever.
> 
> I must say the Ubuntu provided one works ok for me, I upgraded shortly before the 24.04 release. The web UI is completely shot - switching tabs doesn't do anything, but the filtering works.

That's my issue, too.

With my own-built package all works fine. So it would be great to republish a version for 24.04.

Thanks, Uwe

**Comment by fatalbanana** [comment]
Going forward new releases will be published for this platform, starting today with the release of 3.9.0.
