### ISSUE TITLE
[Feature] WebUI pop-up Ham/Spam box

### ISSUE THREAD

**Issue by dehnli** [rspamd/rspamd#676]
On the main page when you hover over Learned section to show the pop-up ham/spam box with the number of messages separately like that `666/6666` or something similar

**Comment by moisseev** [comment]
I think it's not a good idea to mix up different counters. `Learned` counter shows messages learned since statistics reset. Look at numbers in the `rspamc stat` output below.
I think it's better to display bayes classifier statistics separately.
~~~
# rspamc stat
...
Messages learned: 6559
...
Statfile: BAYES_SPAM type: sqlite3; length: 92.90M; free blocks: 0; total blocks: 1.29M; free: 0.00%; learned: 4832; users: 1; languages: 3
Statfile: BAYES_HAM type: sqlite3; length: 97.26M; free blocks: 0; total blocks: 1.31M; free: 0.00%; learned: 5947; users: 1; languages: 3
Total learns: 10779
~~~

**Comment by dehnli** [comment]
I agree. This is what I mean

**Comment by vstakhov** [comment]
That's not possible to do in the current architecture.
