### ISSUE TITLE
Feature request: include p0f fingerprints 

### ISSUE THREAD

**Issue by croessner** [rspamd/rspamd#968]
Hi,

it would be awesome to have p0f included to detect certain operating systems like Windows XP, 7 and 8. Unfortunately all Microsoft OSes appear as Windows 7 or 8, a decision cam not be done hard. Therefore rspamd would be ideal to just add scores.

p0f could help to fight better against zombie PCs.

**Comment by vstakhov** [comment]
In principle, such a plugin can be written using [lua tcp client](https://rspamd.com/doc/lua/tcp.html) and pack/unpack routines from `rspamd_util`.

BTW, your MTA seems to have broken IPv6 support, so my messages are rejected: 

```
host mx.roessner-net.de[2a05:bec0::134:255:226:247] said:
    550-5.7.25 Client host rejected: cannot find your hostname,
    [2a01:4f8:190:43b5::99] 550 5.7.25 For assistance, please provide the
    following information in your problem report: time (Sep 20 11:35:56),
    client (2a01:4f8:190:43b5::99:55702) and server (mx.roessner-net.de). (in
    reply to RCPT TO command)
```

**Comment by croessner** [comment]
@vstakhov thanks for the MX reject report. Even using a local unbound resolver and a second resolver as backup on a physical machine, it sometimes can not directly resolve stuff. I changed from 550 to 450. Feel free to try sending again please 😊

**Comment by heraklit256** [comment]
I would be interested in p0f support, too.

**Comment by vstakhov** [comment]
That looks very good! I just think this should be a part of the lua_scanners framework to be one of the `external_services` plugins type. I'm also not quite sure about caching in Redis in this case: is it anyhow useful?

**Comment by denpamusic** [comment]
Thank you! I'll thought about making it part of that framework but as I created this plugin for myself at first, I wasn't sure how to do it with "plugins.d" mechanism. If you're interested I can redo this as PR for rspamd using scanners framework.

In case of small to medium volume system, working without cache should fine, but on large volume I'm afraid of overloading p0f with requests, since p0f can't really be scaled, doesn't feature any internal caching and by default has a limit of 20 simultaneous connections. It can be risen with -S flag, but author recommends not going overboard with it. There's possibility to make cache optional though, so users decide if it's needed based on their volume.

**Comment by vstakhov** [comment]
It is now implemented, thanks to @denpamusic !
